	db.url=jdbc:mysql://localhost:3306/ecommerce?useSSL=false
	db.user=root
	db.password=zaq12wsx
	
	
	
	
	POST http://127.0.0.1:8080/v2/publish/https://example.com -H "Authorization: Bearer eyJVc2VySUQiOiJkZWZhdWx0VXNlciIsIlBhc3N3b3JkIjoiZGVmYXVsdFBhc3N3b3JkIn0="


v0.2.3.0f
Code: New Year Kiss

v0.2.3.0e:
Code: Ring My Bell

v0.2.3.0d:
Cheat code: Gawain Commando

v0.2.1.1:
Code: Third-Partied

v0.2.0.0a:
code: Breedin Buns

v0.1.4.1:
Album and Cheat code: Freefalling Borker

v0.1.2.7:
Cheat code: Music Review

v1.2.6k - Album Code June: Strict Bunch

March Code: BBQ Shark

v0.1.2.1e - Album Code: Sizzling Hot Ogre
v0.1.1.2h - Album Code: Dragon Snax
v0.1.1.2 - Album Code: Crabby Cheer
v0.1.1.1c - Album Code: Crabby Cheer
v0.1.1.1b - Album Code: Soothing Sutras
v0.1.1.1 - Album Code: Soothing Sutras

v0.1.1.0k : Album code: Soothing Sutras

Gallery Code: Dancing Dragoness
Cheat code: Washboard Abs (v0.1.1.0b)

Old codes:
UnlockAllCode = "Mop Diva";
UnlockAllCode = "Scribble Owl";
UnlockAllCode = "Sprites Sprites Everywhere";
GodMode = "What Is Damage";
MoneyCode = "Money Money Money";
CombatCode = "Take Me To Fight";
ResetCode = "Reset";