spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zaq12wsx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
