eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zaq12wsx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect